namespace System.Numerics;

#pragma warning disable IDE0055, IDE0007, IDE0047

// call in right cases
// this version combines 128 and 256 ways into one
public static partial class Mat44
{
    [MethodImpl(AggressiveInlining)]
    internal static Mat44<T> RotateV2<T>(Mat44<T> m, Quat<T> r)
        where T : unmanaged, INumber<T>, IRootFunctions<T>, ITrigonometricFunctions<T>
    {
        Vec4<T> z = r.Vec4(), x = z.YZXW(), y = z.WWWW(), c = z.ZXYW(), d,

        w = x * x; // yy, zz, xx, ww
        x = z * x; // xy, yz, xz, ww
        y = c * y; // zw, xw, yw, ww

        (d, c) = (x + y, x - y);     // xy +/- zw      | yz +/- xw      | xz +/- yw      | 2ww, no mean / 0

        d = d.ZXYW(); w += w.YZXW();
        d += d;                      // 2(xz + yw)     | 2(xy + zw)     | 2(yz + xw)     | 4ww, no mean     || q31, q12, q23
        c += c;                      // 2(xy - zw)     | 2(yz - xw)     | 2(xz - yw)     | 0                || q21, q32, q13
        w = SizeOf<T>() == 4         // 1 - 2(yy + zz) | 1 - 2(zz + xx) | 1 - 2(xx + yy) | 1 - 4ww, no mean || q11, q22, q33
            ? Vector128<T>.One.Vec4() - (w + w)
            : Vector256<T>.One.Vec4() - (w + w); // Vec4<T>.One currently provokes unnecessary transfers generated by JIT

        x = m.X * w;                   // mx(x, y, z, w) * (q11, q22, q33, -)
        x = m.X.YZXW().Estimate(c, x); // mx(y, z, x, w) * (q21, q32, q13, -) + ...
        x = m.X.ZXYW().Estimate(d, x); // mx(z, x, y, w) * (q31, q12, q23, -) + ...

        y = m.Y * w;                   // my(x, y, z, w) * (q11, q22, q33, -)
        y = m.Y.YZXW().Estimate(c, y); // my(y, z, x, w) * (q21, q32, q13, -) + ...
        y = m.Y.ZXYW().Estimate(d, y); // my(z, x, y, w) * (q31, q12, q23, -) + ...

        z = m.Z * w;                   // mz(x, y, z, w) * (q11, q22, q33, -)
        z = m.Z.YZXW().Estimate(c, z); // mz(y, z, x, w) * (q21, q32, q13, -) + ...
        z = m.Z.ZXYW().Estimate(d, z); // mz(z, x, y, w) * (q31, q12, q23, -) + ...

        w = m.W * w;                   // mw(x, y, z, w) * (q11, q22, q33, -)
        w = m.W.YZXW().Estimate(c, w); // mw(y, z, x, w) * (q21, q32, q13, -) + ...
        w = m.W.ZXYW().Estimate(d, w); // mw(z, x, y, w) * (q31, q12, q23, -) + ...

        m.X = x.Insert(3, 3, m.X);
        m.Y = y.Insert(3, 3, m.Y);
        m.Z = z.Insert(3, 3, m.Z);
        m.W = w.Insert(3, 3, m.W);

        return m;
    }
}
