namespace System.Numerics;

#pragma warning disable IDE0055, IDE0007, IDE0047

// calls in right cases
// this version combines 128 and 256 ways into one
public static partial class Mat44
{
    /// <inheritdoc cref="Affine{T}(Quat{T}, Vec3{T}, Vec3{T})"/>
    [MethodImpl(AggressiveInlining)]
    private static unsafe Mat44<T> Affine<T>(Vec4<T> r, in Vec3<T> s, Vec3<T> t)
        where T : unmanaged, INumber<T>, IRootFunctions<T>, ITrigonometricFunctions<T>
    {
        var m = Rotation(r);

        fixed (Vec3<T>* p = &s)
        {
            m.X *= *(T*)p;
            m.Y *= *((T*)p + 1);
            m.Z *= *((T*)p + 2);
        }
        m.W = SizeOf<T>() == 4 ? t.As128One().Vec4() : t.As256One().Vec4();

        return m;
    }

    /// <inheritdoc cref="Rotation{T}(Quat{T})"/>
    [MethodImpl(AggressiveInlining)]
    private static Mat44<T> Rotation<T>(Vec4<T> w)
        where T : unmanaged, INumber<T>, IRootFunctions<T>, ITrigonometricFunctions<T>
    {
        Vec4<T> z = w.ZXYW(),

        x = w.YZXW() * w, // xy, yz, xz, ww
        y = w.WWWW() * z; // zw, xw, yw, ww
        w *= w;           // xx, yy, zz, ww

        (x, z) = (x + y, x - y); // xy +\- zw  | yz +\- xw  | xz +\- yw  | 2ww (no mean) \ 0
        x += x;                  // 2(xy + zw) | 2(yz + xw) | 2(xz + yw) | 4ww (no mean)
        z += z;                  // 2(xy - zw) | 2(yz - xw) | 2(xz - yw) | 0
        w += w.YZXW();           // xx + yy    | yy + zz    | zz + xx    | 4ww (no mean)

        w = SizeOf<T>() == 4     // 1 - 2(xx + yy) | 1 - 2(yy + zz) | 1 - 2(zz + xx) | 1 - 4ww, no mean
           ? Vector128<T>.One.Vec4() - (w + w)
           : Vector256<T>.One.Vec4() - (w + w); // Vec4<T>.One currently provokes unnecessary transfers generated by JIT

        Mat44<T> m;

        m.X = z.Insert(0, 1, w).Insert(1, 0, x); // 1 - 2(yy + zz) | 2(xy + zw)     | 2(xz - yw)     | 0
        m.Y = z.Insert(1, 2, w).Insert(2, 1, x); // 2(xy - zw)     | 1 - 2(zz + xx) | 2(yz + xw)     | 0
        m.Z = z.Insert(0, 2, x).Insert(2, 0, w); // 2(xz + yw)     | 2(yz - xw)     | 1 - 2(xx + yy) | 0

        m.W = SizeOf<T>() == 4  // JIT compiler currently can't move Vec4<T>.UnitW to a vector register outside the loop without bitcasting
           ? Vec4<T>.UnitW.As128().Vec4()
           : Vec4<T>.UnitW.As256().Vec4();

        return m;
    }

    [MethodImpl(AggressiveInlining)]
    private static Mat44<T> Rotate<T>(Mat44<T> m, Vec4<T> w)
        where T : unmanaged, INumber<T>, IRootFunctions<T>, ITrigonometricFunctions<T>
    {
        Vec4<T> x = w.YZXW(), y = w.WWWW(), c = w.ZXYW(), d,

        z = x * x; // yy, zz, xx, ww
        x = w * x; // xy, yz, xz, ww
        y = c * y; // zw, xw, yw, ww

        (d, c) = (x + y, x - y);     // xy +/- zw      | yz +/- xw      | xz +/- yw      | 2ww, no mean / 0

        d = d.ZXYW(); z += z.YZXW();
        d += d;                      // 2(xz + yw)     | 2(xy + zw)     | 2(yz + xw)     | 4ww, no mean     || q31, q12, q23
        c += c;                      // 2(xy - zw)     | 2(yz - xw)     | 2(xz - yw)     | 0                || q21, q32, q13
        z = SizeOf<T>() == 4         // 1 - 2(yy + zz) | 1 - 2(zz + xx) | 1 - 2(xx + yy) | 1 - 4ww, no mean || q11, q22, q33
            ? Vector128<T>.One.Vec4() - (z + z)
            : Vector256<T>.One.Vec4() - (z + z); // Vec4<T>.One currently provokes unnecessary transfers generated by JIT

        x = m.X * z;                   // mx(x, y, z, w) * (q11, q22, q33, -)
        x = m.X.YZXW().Estimate(c, x); // mx(y, z, x, w) * (q21, q32, q13, -) + ...
        x = m.X.ZXYW().Estimate(d, x); // mx(z, x, y, w) * (q31, q12, q23, -) + ...

        y = m.Y * z;                   // my(x, y, z, w) * (q11, q22, q33, -)
        y = m.Y.YZXW().Estimate(c, y); // my(y, z, x, w) * (q21, q32, q13, -) + ...
        y = m.Y.ZXYW().Estimate(d, y); // my(z, x, y, w) * (q31, q12, q23, -) + ...

        z = m.Z * z;                   // mz(x, y, z, w) * (q11, q22, q33, -)
        z = m.Z.YZXW().Estimate(c, z); // mz(y, z, x, w) * (q21, q32, q13, -) + ...
        z = m.Z.ZXYW().Estimate(d, z); // mz(z, x, y, w) * (q31, q12, q23, -) + ...

        w = m.W * z;                   // mw(x, y, z, w) * (q11, q22, q33, -)
        w = m.W.YZXW().Estimate(c, w); // mw(y, z, x, w) * (q21, q32, q13, -) + ...
        w = m.W.ZXYW().Estimate(d, w); // mw(z, x, y, w) * (q31, q12, q23, -) + ...

        m.X = x.Insert(3, 3, m.X);
        m.Y = y.Insert(3, 3, m.Y);
        m.Z = z.Insert(3, 3, m.Z);
        m.W = w.Insert(3, 3, m.W);

        return m;
    }
}
